"""add translation columns

Revision ID: 83be2890aeaa
Revises: 
Create Date: 2026-03-18 13:05:27.498095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83be2890aeaa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('name_de', sa.String(length=200), nullable=True))
    op.add_column('ingredients', sa.Column('name_en', sa.String(length=200), nullable=True))
    op.add_column('ingredients', sa.Column('unit_de', sa.String(length=50), nullable=True))
    op.add_column('ingredients', sa.Column('unit_en', sa.String(length=50), nullable=True))
    op.drop_column('ingredients', 'name')
    op.drop_column('ingredients', 'unit')
    op.add_column('recipes', sa.Column('title_de', sa.String(length=100), nullable=True))
    op.add_column('recipes', sa.Column('title_en', sa.String(length=100), nullable=True))
    op.add_column('recipes', sa.Column('description_de', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('origin_country_de', sa.String(length=100), nullable=True))
    op.add_column('recipes', sa.Column('origin_country_en', sa.String(length=100), nullable=True))
    op.add_column('recipes', sa.Column('origin_region_de', sa.String(length=100), nullable=True))
    op.add_column('recipes', sa.Column('origin_region_en', sa.String(length=100), nullable=True))
    op.drop_column('recipes', 'origin_region')
    op.drop_column('recipes', 'origin_country')
    op.drop_column('recipes', 'description')
    op.drop_column('recipes', 'title')
    op.add_column('steps', sa.Column('instruction_de', sa.Text(), nullable=True))
    op.add_column('steps', sa.Column('instruction_en', sa.Text(), nullable=True))
    op.drop_column('steps', 'instruction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('instruction', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('steps', 'instruction_en')
    op.drop_column('steps', 'instruction_de')
    op.add_column('recipes', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('origin_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('origin_region', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('recipes', 'origin_region_en')
    op.drop_column('recipes', 'origin_region_de')
    op.drop_column('recipes', 'origin_country_en')
    op.drop_column('recipes', 'origin_country_de')
    op.drop_column('recipes', 'description_en')
    op.drop_column('recipes', 'description_de')
    op.drop_column('recipes', 'title_en')
    op.drop_column('recipes', 'title_de')
    op.add_column('ingredients', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ingredients', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('ingredients', 'unit_en')
    op.drop_column('ingredients', 'unit_de')
    op.drop_column('ingredients', 'name_en')
    op.drop_column('ingredients', 'name_de')
    # ### end Alembic commands ###
