"""changed new tables to not nullable

Revision ID: 8cd8ec00a8b7
Revises: 83be2890aeaa
Create Date: 2026-03-18 14:13:35.083735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd8ec00a8b7'
down_revision: Union[str, Sequence[str], None] = '83be2890aeaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients', 'name_de',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('ingredients', 'name_en',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('recipes', 'title_de',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('recipes', 'title_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('recipes', 'description_de',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('recipes', 'description_en',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('steps', 'instruction_de',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('steps', 'instruction_en',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('steps', 'instruction_en',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('steps', 'instruction_de',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('recipes', 'description_en',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('recipes', 'description_de',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('recipes', 'title_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('recipes', 'title_de',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ingredients', 'name_en',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('ingredients', 'name_de',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
